#!/usr/bin/python
import functools

def debug(func=None, *, prefix=''):
	if func is None:
		return functools.partial(debug, prefix='')
	else:
#	def inner(func):
		# func is function
		x = func.__qualname__
		@functools.wraps(func)
		def wrapper(*args, **kwargs):
			print(x)
			print(func.__name__)
			return func(*args, **kwargs)
#		return wrapper
		return wrapper
@debug(prefix='d')
def plus(a, b):
	return a + b
plus(3, 4)

#ClassDecorator

