development:
  adapter: sqlite3
  encoding: unicode
  database: db/db.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: myapp_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5

